engines:
  duplication:
    enabled: true
    config:
      languages:
        javascript:
          mass_threshold: 40
  eslint:
    enabled: true
    checks:
      keyword-spacing:
        enabled: false
  fixme:
    enabled: true
ratings:
  paths:
  - "src/**.js"
exclude_paths:
- "*.*"
- ".*"
- test/
- selenium-tests/
- node_modules/
- dist/
