sudo: false
language: node_js

node_js:
  - "5"

env:
  - CXX=g++-4.8

before_script:
  - npm install -g gulp http-server codeclimate-test-reporter

script:
  - npm run test
  - npm run build
  - http-server ./dist --silent -p 8080 -a 0.0.0.0 &
  - cd selenium-tests
  - mvn -q test -Dremote=sauce
  - cd ..

after_script:
  - fuser -k 8080/tcp > /dev/null
  - codeclimate-test-reporter < coverage/lcov/lcov.info

cache:
  directories:
    - node_modules

notifications:
  email:
    recipients:
      - ndlu2@illinois.edu
      - alleyao@gmail.com

    on_success: [change]
    on_failure: [change]

addons:
  code_climate:
      repo_token: 871bafd173f6287c809f1460eca1b32082f5ed973b1ea9f8a00d044efc165d0a
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - libopencv-dev
      - g++-4.8

  sauce_connect: true
