language: node_js

node_js:
  - "5"

before_script:
  - npm install -g gulp codeclimate-test-reporter

script: 
  - gulp &
  - sleep 30
  - cd selenium-tests
  - mvn -q test -Dbrowser=remote-firefox
  - cd ..

after_script:
  - fuser -k 8080/tcp > /dev/null
  - codeclimate-test-reporter < coverage/lcov/lcov.info

notifications:
  email:
    recipients:
      - ndlu2@illinois.edu

    on_success: [change]
    on_failure: [change]

addons:
  code_climate:
      repo_token: f5f805b760659243b4a91da98dbd6f2da835a96bf80cc8f1d534ab153e355b76
  apt:
    packages:
    - libopencv-dev
  sauce_connect: true
