#!/bin/bash

function stop {
	killall Xvfb
	fuser -k 8080/tcp > /dev/null
}

function start {
	stop
	Xvfb :99 &
	export DISPLAY=:99
	npm install --no-bin-links > /dev/null
	gulp &
}

if [[ "$1" = "start" ]]; then
	start
elif [[ "$1" = "stop" ]]; then
	stop
else
	start
	cd selenium-tests
	sleep 10
	mvn test
	cd ..
	stop
fi
