#!/bin/bash

function stop {
	killall Xvfb
	fuser -k 8080/tcp > /dev/null
}

function start {
	stop
	Xvfb :99 -screen 0 1024x768x16 &
	export DISPLAY=:99
	npm install
	gulp &
}
function remove {
	rm selenium-tests/src/test/resources/edge.png
	rm selenium-tests/src/test/resources/integration.png
	rm selenium-tests/src/test/resources/no_edge.png
}

if [[ "$1" = "start" ]]; then
	start
elif [[ "$1" = "stop" ]]; then
	stop
elif [[ "$1" = "remove" ]]; then
	remove
else
	start
	cd selenium-tests
	sleep 10
	mvn test
	cd ..
	stop
fi
